version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/ci-build/
    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker login -u $REDHAT_USER -p $REDHAT_PASS registry.redhat.io

          docker build -t labsai/base-image:redhat-b$CIRCLE_BUILD_NUM .
          docker build -t labsai/base-image:redhat-latest .
          docker build -t registry.redhat.io/labsai/base-image:redhat-b$CIRCLE_BUILD_NUM .
          docker build -t registry.redhat.io/labsai/base-image:redhat-latest .

          docker push registry.redhat.io/labsai/base-image:redhat-b$CIRCLE_BUILD_NUM
          docker push registry.redhat.io/labsai/base-image:redhat-latest

          docker login -u $DOCKER_USER -p $DOCKER_PASS

          docker push labsai/base-image:redhat-b$CIRCLE_BUILD_NUM
          docker push labsai/base-image:redhat-latest
